sectors:
  SOCIAL:
    keywords:
      [
        "трудов",
        "зарплат",
        "охорона прац",
        "єсв",
        "пенсій",
        "страхуван",
        "лікарнян",
        "відпустк",
      ]
    weight: 2
  AGRI:
    keywords:
      [
        "земельн",
        "пай",
        "субсид",
        "експорт",
        "квот",
        "фітосан",
        "зерн",
        "насінн",
        "ветеринар",
        "добрив",
      ]
    weight: 3
  CORPORATE:
    keywords:
      [
        "подат",
        "пдв",
        "акциз",
        "валют",
        "корпоратив",
        "m&a",
        "злитт",
        "поглинан",
        "трансферт",
        "реєстрац",
        "капітал",
      ]

risk:
  boosters:
    - pattern: "штраф|відповідальн|санкц"
      score: 20
    - pattern: "обов'?язков|припиненн|заборон"
      score: 15
    - pattern: "кодекс|податковий|кзпп|земельний"
      score: 10
  dampers:
    - pattern: "тимчасов|пілотн|експеримент"
      score: -5
levels:
  LOW: "<=20"
  MEDIUM: "<=40"
  HIGH: ">40"
